apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: css
  namespace: default
spec:
  rules:
    - host: css-external.pl
      http:
        paths:
          - path: /api/v1
            backend:
              serviceName: api
              servicePort: 80

