apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-proj1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
  storageClassName: normal
